exclude:
  - '**/tests/**'
  - '**/vendor/**'
  - '**/*.d.ts'
  - 'scripts/**'

sourcemap: false
instrument: false

extension: ['.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx', '.svelte']

reporter: ["text", "json"]
