//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "admin_notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub notification_id: i64,
    pub site_id: Option<i32>,
    pub body: Option<String>,
    pub r#type: Option<String>,
    pub viewed: Option<bool>,
    pub date: Option<DateTime>,
    pub extra: Option<Vec<u8>>,
    pub notify_online: Option<bool>,
    pub notify_feed: Option<bool>,
    pub notify_email: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::site::Entity",
        from = "Column::SiteId",
        to = "super::site::Column::SiteId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Site,
}

impl Related<super::site::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Site.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
