//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "files_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub file_event_id: i64,
    pub filename: Option<String>,
    pub date: Option<DateTime>,
    pub user_id: Option<i32>,
    pub user_string: Option<String>,
    pub action: Option<String>,
    pub action_extra: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
