/*
 * lib.rs
 *
 * DEEPWELL - Wikijump API provider and database manager
 * Copyright (C) 2019-2025 Wikijump Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

//! Library version of the deepwell crate.
//!
//! This allows you to customize how the server is run, and work with
//! the crate's types and systems.
//!
//! The supported embedding facade is `config`, `runtime`, `services`, `types`,
//! and the server startup functions re-exported from `start`. Infrastructure
//! modules are public because the binary is a separate crate target. `endpoints`
//! and `models` remain public for the direct integration-test harness and
//! migration tooling; their paths are internal contracts and may change with
//! Deepwell and Framerail in the same delivery.

#[macro_use]
extern crate exn;

#[macro_use]
extern crate log;

#[macro_use]
extern crate futures;

#[macro_use]
extern crate serde;

#[macro_use]
extern crate static_assertions;

#[macro_use]
extern crate str_macro;

#[macro_use]
mod macros;

// Auto-generated by sea-orm-cli
#[allow(unused_imports)]
pub mod models;

#[cfg(feature = "watch")]
mod watch;

// Server entrypoint
mod start;

pub mod api;
pub mod config;
pub mod constants;
pub mod database;
pub mod endpoints;
pub mod error;
pub mod hash;
pub mod info;
pub mod license;
pub mod locales;
pub mod middleware;
pub mod redis;
pub mod runtime;
pub mod services;
pub mod types;
pub mod utils;

pub use self::start::*;
