//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "site")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub site_id: i64,
    pub name: Option<String>,
    pub subtitle: Option<String>,
    #[sea_orm(unique)]
    pub unix_name: Option<String>,
    pub description: Option<String>,
    pub language: String,
    pub date_created: Option<DateTime>,
    pub custom_domain: Option<String>,
    pub visible: bool,
    pub default_page: String,
    pub private: bool,
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::admin::Entity")]
    Admin,
    #[sea_orm(has_many = "super::admin_notification::Entity")]
    AdminNotification,
    #[sea_orm(has_many = "super::category::Entity")]
    Category,
    #[sea_orm(has_many = "super::domain_redirect::Entity")]
    DomainRedirect,
    #[sea_orm(has_many = "super::email_invitation::Entity")]
    EmailInvitation,
    #[sea_orm(has_many = "super::file::Entity")]
    File,
    #[sea_orm(has_many = "super::forum_group::Entity")]
    ForumGroup,
    #[sea_orm(has_many = "super::forum_post::Entity")]
    ForumPost,
    #[sea_orm(has_many = "super::forum_settings::Entity")]
    ForumSettings,
    #[sea_orm(has_many = "super::forum_thread::Entity")]
    ForumThread,
    #[sea_orm(has_many = "super::front_forum_feed::Entity")]
    FrontForumFeed,
    #[sea_orm(has_many = "super::ip_block::Entity")]
    IpBlock,
    #[sea_orm(has_many = "super::member::Entity")]
    Member,
    #[sea_orm(has_many = "super::member_application::Entity")]
    MemberApplication,
    #[sea_orm(has_many = "super::member_invitation::Entity")]
    MemberInvitation,
    #[sea_orm(has_many = "super::page::Entity")]
    Page,
    #[sea_orm(has_many = "super::site_settings::Entity")]
    SiteSettings,
    #[sea_orm(has_many = "super::site_viewer::Entity")]
    SiteViewer,
    #[sea_orm(has_many = "super::theme::Entity")]
    Theme,
    #[sea_orm(has_many = "super::forum_category::Entity")]
    ForumCategory,
    #[sea_orm(has_many = "super::moderator::Entity")]
    Moderator,
    #[sea_orm(has_many = "super::user_block::Entity")]
    UserBlock,
}

impl Related<super::admin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Admin.def()
    }
}

impl Related<super::admin_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminNotification.def()
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::domain_redirect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DomainRedirect.def()
    }
}

impl Related<super::email_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailInvitation.def()
    }
}

impl Related<super::file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::File.def()
    }
}

impl Related<super::forum_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ForumGroup.def()
    }
}

impl Related<super::forum_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ForumPost.def()
    }
}

impl Related<super::forum_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ForumSettings.def()
    }
}

impl Related<super::forum_thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ForumThread.def()
    }
}

impl Related<super::front_forum_feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FrontForumFeed.def()
    }
}

impl Related<super::ip_block::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IpBlock.def()
    }
}

impl Related<super::member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Member.def()
    }
}

impl Related<super::member_application::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemberApplication.def()
    }
}

impl Related<super::member_invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemberInvitation.def()
    }
}

impl Related<super::page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Page.def()
    }
}

impl Related<super::site_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteSettings.def()
    }
}

impl Related<super::site_viewer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteViewer.def()
    }
}

impl Related<super::theme::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Theme.def()
    }
}

impl Related<super::forum_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ForumCategory.def()
    }
}

impl Related<super::moderator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Moderator.def()
    }
}

impl Related<super::user_block::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBlock.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
