//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_settings")]
pub struct Model {
    pub user_id: Option<i32>,
    pub receive_invitations: bool,
    pub receive_pm: String,
    pub notify_online: String,
    pub notify_feed: String,
    pub notify_email: Option<String>,
    pub receive_newsletter: bool,
    pub receive_digest: bool,
    pub allow_site_newsletters_default: bool,
    pub max_sites_admin: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
