# Config documentation: https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#configuration-options-for-dependabotyml

version: 2
updates:
  # Frontend
  - package-ecosystem: npm
    directory: "/framerail"
    schedule:
      interval: weekly

  # DEEPWELL
  - package-ecosystem: cargo
    directory: "/deepwell"
    schedule:
      interval: weekly

  # WWS
  - package-ecosystem: cargo
    directory: "/wws"
    schedule:
      interval: weekly
