# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true

issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels:
        - "coderabbit-plan"
        - "!no-plan"
  labeling:
    auto_apply_labels: true
