//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use super::sea_orm_active_enums::AliasType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub alias_id: i64,
    pub alias_type: AliasType,
    pub created_at: OffsetDateTime,
    pub created_by: i64,
    pub target_id: i64,
    pub slug: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl ActiveModelBehavior for ActiveModel {}
