//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub comment_id: i64,
    pub page_id: Option<i32>,
    pub parent_id: Option<i32>,
    pub user_id: Option<i32>,
    pub user_string: Option<String>,
    pub title: Option<String>,
    pub text: Option<String>,
    pub date_posted: Option<DateTime>,
    pub site_id: Option<i32>,
    pub revision_number: i32,
    pub revision_id: Option<i32>,
    pub date_last_edited: Option<DateTime>,
    pub edited_user_id: Option<i32>,
    pub edited_user_string: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
