//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "global_user_block")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub block_id: i64,
    pub site_id: Option<i32>,
    pub user_id: Option<i32>,
    pub reason: Option<String>,
    pub date_blocked: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
