//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use super::sea_orm_active_enums::InteractionObjectType;
use super::sea_orm_active_enums::InteractionType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "interaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_type: InteractionObjectType,
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub interaction_type: InteractionType,
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_type: InteractionObjectType,
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_id: i64,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
