//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "interactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub setter_type: String,
    pub setter_id: i32,
    pub interaction_type: i16,
    pub target_type: String,
    pub target_id: i32,
    pub metadata: Option<Json>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
