//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "membership_link")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub link_id: i64,
    pub site_id: Option<i32>,
    pub by_user_id: Option<i32>,
    pub user_id: Option<i32>,
    pub date: Option<DateTime>,
    pub r#type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
