//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

// Disable clippy lints for autogenerated files
#![allow(clippy::all)]

pub mod prelude;

pub mod file;
pub mod file_revision;
pub mod page;
pub mod page_attribution;
pub mod page_category;
pub mod page_connection;
pub mod page_connection_missing;
pub mod page_link;
pub mod page_lock;
pub mod page_parent;
pub mod page_revision;
pub mod page_vote;
pub mod sea_orm_active_enums;
pub mod site;
pub mod system_filter;
pub mod text;
pub mod user;
pub mod user_alias;
pub mod user_bot_owner;
