//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

// Disable clippy lints for autogenerated files
#![allow(clippy::all)]

pub mod prelude;

pub mod file;
pub mod file_revision;
pub mod forum_category;
pub mod forum_group;
pub mod forum_post;
pub mod forum_thread;
pub mod page;
pub mod page_category;
pub mod page_connection;
pub mod page_connection_missing;
pub mod page_link;
pub mod page_parent;
pub mod page_revision;
pub mod page_vote;
pub mod sea_orm_active_enums;
pub mod settings;
pub mod site;
pub mod site_settings;
pub mod text;
pub mod user_block;
pub mod user_messages;
pub mod users;
