//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub notification_id: i64,
    pub user_id: Option<i32>,
    pub body: Option<String>,
    pub r#type: Option<String>,
    pub viewed: bool,
    pub date: Option<DateTime>,
    pub extra: Option<Vec<u8>>,
    pub notify_online: bool,
    pub notify_feed: bool,
    pub notify_email: bool,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
