//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "page_connection_missing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub from_page_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub to_page_slug: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub connection_type: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
