//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "page_edit_lock")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub lock_id: i64,
    pub page_id: Option<i32>,
    pub page_unix_name: Option<String>,
    pub user_id: Option<i32>,
    pub user_string: Option<String>,
    pub session_id: Option<String>,
    pub date_started: Option<DateTime>,
    pub date_last_accessed: Option<DateTime>,
    pub secret: Option<String>,
    pub site_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::page::Entity",
        from = "Column::PageId",
        to = "super::page::Column::PageId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Page,
}

impl Related<super::page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Page.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
