//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "page_connection_missing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub from_page_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub to_site_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub to_page_slug: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub connection_type: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::page::Entity",
        from = "Column::FromPageId",
        to = "super::page::Column::PageId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Page2,
    #[sea_orm(
        belongs_to = "super::page::Entity",
        from = "Column::ToSiteId",
        to = "super::page::Column::PageId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Page1,
}

impl ActiveModelBehavior for ActiveModel {}
