//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use super::sea_orm_active_enums::SystemFilterType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "system_filter")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub filter_id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub filter_type: SystemFilterType,
    #[sea_orm(column_type = "Text")]
    pub regex: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
