//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::types::TextBlockType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "text_block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub block_type: TextBlockType,
    #[sea_orm(primary_key, auto_increment = false)]
    pub page_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub block_index: i16,
    #[sea_orm(column_type = "Text", unique)]
    pub s3_filename: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub block_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::page::Entity",
        from = "Column::PageId",
        to = "super::page::Column::PageId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Page,
}

impl Related<super::page::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Page.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
