/*
 * handler/misc.rs
 *
 * Wilson's Web Server - Serves a zoo of user-generated content
 * Copyright (C) 2019-2026 Wikijump Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use crate::state::ServerState;
use axum::body::Body;
use axum::extract::{Path, State};
use axum::http::header;
use axum::http::status::StatusCode;
use axum::response::Response;

const HTML_BLOCK_CSS: &str = r#"/* CSS used inside of iframes generated by [[html]] blocks */

html#html-block-html, html#html-block-html body {
    padding: 0;
    margin: 0;
    overflow: hidden;
    background: transparent;
}

/* The following rule makes iframe auto-shrink */

html#html-block-html body {
    height: auto;
}

"#;

const HTML_BLOCK_IFRAME_JS: &str = r##"(function() {
    // running in private context, no namespace pollution :-)

    var delay = 250; // each 250 ms, content height will be checked
    var current_height = 0; // assume starting height is 0px

    // other arguments are passed in URL, for example:
    //  http://www.wdfiles.dev/local--html/start/5d5a0384a922dd96ac0db81d715a5bf348d43c57/www.wikidot.dev/?ukey=1b91d581807e1ba924db3d456f2b8f43b51a1ea0
    //  ^ keep the same protocol (http/https)    ^ iframe hash to pass when resizing      ^ original domain     ^ authorization key
    var url_array = location.toString().split('/');
    var iframe_hash = url_array[5];
    var resize_domain = url_array[6];
    if (/^\d+$/.test(resize_domain) && url_array[3] == '-' && url_array[4] == 'html') {
        var referrer_match = document.referrer.match(/^https?:\/\/([^\/]+)/);
        iframe_hash = resize_domain;
        resize_domain = referrer_match ? referrer_match[1] : location.host.replace('.wjfiles.', '.wikijump.');
    }
    var random = Math.random();
    var resize_div_id = 'div_' + iframe_hash + random;
    var resize_iframe_id = 'iframe_' + iframe_hash + random;
    var resize_url = url_array[0] + '//' + resize_domain + '/common--javascript/resize-iframe.html';
    //               ^ http:               ^ www.wikidot.dev (original domain)

    var get_height = function() {
        if (document.body.scrollHeight) {
            return document.body.scrollHeight;
        }
        if (document.height) {
            return document.height;
        }
        return document.body.offsetHeight;
    };

    var resize = function() {
        var div = document.getElementById(resize_div_id);

        var old_iframe = document.getElementById(resize_iframe_id);
        if (old_iframe) {
            div.removeChild(old_iframe);
            delete old_iframe;
        }

        var iframe = document.createElement("iframe");
        iframe.id = resize_iframe_id;
        iframe.src = resize_url + "?" + Math.random() + "#" + current_height + "/" + iframe_hash;
        div.appendChild(iframe);
    };

    // every <delay> miliseconds:
    // if height changed from last time, do resize
    var tick = function() {
        var new_height = get_height();
        if (new_height != current_height) {
            current_height = new_height;
            resize(current_height);
        }
        setTimeout(tick, delay);
    };

    var init = function() {
        var div = document.createElement("div");
        div.id = resize_div_id;
        div.setAttribute('style', 'display: none');
        div.style.display = 'none'; // this way it works even in IE
        document.body.appendChild(div);
        tick();
    };

    var old_onload = window.onload;
    window.onload = function() {
        if (typeof(old_onload) == "function") {
            old_onload();
        }
        init();
    };
})();
"##;

const RESIZE_IFRAME_HTML: &str = r#"<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
<title></title>
<script type="text/javascript">

var hash = location.hash.toString();
var hash_a1 = hash.split('/');
var hash_a2 = hash_a1[0].split('#');
var id = hash_a1[1];
var height = hash_a2[1];

parent.parent.$j('iframe.html-block-iframe[src$="/' + id + '"]').height(height + 'px');

</script>
</head>
<body>
<!--

This HTML is meant to be iframed in an iframe in order to do cross-domain iframe resizing.

From parent.parent window, jQuery and document objects are grabbed.
Iframe with class "html-block-iframe" and src ending with <src> is matched
and resized to height <height> px using jQuery.

<src> and <height> are grabbed from URL of this iframe, format:

http://<domain>/common-javascript/resize-iframe.html#<height>/<src>

<domain> may be at wikidot.com or custom domain.
It must be the same as the parent.parent's domain.

-->
</body>
</html>
"#;

fn text_response(body: &'static str, status: StatusCode) -> Response {
    Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "text/plain; charset=utf-8")
        .body(Body::from(body))
        .expect("Unable to convert response data")
}

fn static_response(body: &'static str, content_type: &'static str) -> Response {
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, content_type)
        .body(Body::from(body))
        .expect("Unable to convert response data")
}

pub async fn handle_health_check(State(state): State<ServerState>) -> Response {
    // DEEPWELL's ping ensures both Postgres and Redis are connected
    match state.deepwell.ping().await {
        Ok(()) => text_response("✅", StatusCode::OK),
        Err(error) => {
            error!("Unable to perform health check: {error}");
            text_response("❌", StatusCode::SERVICE_UNAVAILABLE)
        }
    }
}

pub async fn handle_common_theme(Path(path): Path<String>) -> StatusCode {
    warn!(path = path, "Unknown common theme resource");
    StatusCode::NOT_FOUND
}

pub async fn handle_html_block_css() -> Response {
    static_response(HTML_BLOCK_CSS, "text/css")
}

pub async fn handle_common_javascript(Path(path): Path<String>) -> StatusCode {
    warn!(path = path, "Unknown common JavaScript resource");
    StatusCode::NOT_FOUND
}

pub async fn handle_html_block_iframe_js() -> Response {
    static_response(HTML_BLOCK_IFRAME_JS, "application/x-javascript")
}

pub async fn handle_resize_iframe_html() -> Response {
    static_response(RESIZE_IFRAME_HTML, "text/html")
}

pub async fn handle_invalid_method() -> StatusCode {
    StatusCode::METHOD_NOT_ALLOWED
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body;

    #[tokio::test]
    async fn text_response_sets_status_content_type_and_body() {
        let response = text_response("ready", StatusCode::OK);

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "text/plain; charset=utf-8",
        );
        let body = body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        assert_eq!(&body[..], b"ready");
    }

    #[tokio::test]
    async fn html_block_css_is_served_with_css_type() {
        let response = handle_html_block_css().await;

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "text/css"
        );
        let body = body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        assert!(String::from_utf8_lossy(&body).contains("html#html-block-html"));
    }

    #[tokio::test]
    async fn html_block_iframe_script_is_served_with_javascript_type() {
        let response = handle_html_block_iframe_js().await;

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/x-javascript",
        );
        let body = body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        let body = String::from_utf8_lossy(&body);
        assert!(body.contains("resize_url"));
        assert!(body.contains("document.referrer"));
        assert!(body.contains("location.host.replace('.wjfiles.', '.wikijump.')"));
    }

    #[tokio::test]
    async fn resize_iframe_html_is_served_with_html_type() {
        let response = handle_resize_iframe_html().await;

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "text/html"
        );
        let body = body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        assert!(String::from_utf8_lossy(&body).contains("iframe.html-block-iframe"));
    }

    #[tokio::test]
    async fn unknown_common_resources_are_not_served_by_catch_all() {
        assert_eq!(
            handle_common_theme(Path("base/css/style.css".into())).await,
            StatusCode::NOT_FOUND,
        );
        assert_eq!(
            handle_common_javascript(Path("other.js".into())).await,
            StatusCode::NOT_FOUND,
        );
    }

    #[tokio::test]
    async fn invalid_methods_are_rejected() {
        assert_eq!(
            handle_invalid_method().await,
            StatusCode::METHOD_NOT_ALLOWED
        );
    }
}
