[package]
name = "deepwell"
default-run = "deepwell"
description = "DEEPWELL - Wikijump API provider and database manager"
repository = "https://github.com/scpwiki/wikijump/tree/develop/deepwell"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["wikijump", "api", "backend", "wiki"]
categories = ["asynchronous", "database", "web-programming::http-server"]
exclude = [".gitignore", ".editorconfig"]

version = "2026.7.22"
authors = ["Emmie Smith <emmie.maeda@gmail.com>"]
edition = "2024"
rust-version = "1.95.0"

[features]
watch = ["notify"]

[dependencies]
argon2 = "0.6.0-rc.8"
arraystring = "0.3"
askama = "0.16"
bytes = "1"
cfg-if = "1"
clap = "4"
color-backtrace = "0.7"
cuid2 = "0.1"
data-encoding = "2"
dotenvy = "0.15"
exn = "0.3"
femme = "2"
filemagic = "0.13"
fluent = "0.17"
fluent-syntax = "0"
ftml = { git = "https://github.com/Rokurolize/ftml", rev = "5d27007c394cfa22206390dbec2e43821450c101" }
futures = { version = "0.3", features = ["async-await"], default-features = false }
hex = { version = "0.4", features = ["serde"] }
hostname = "0.4"
intl-memoizer = "0.5"
http = "1.4"
jsonrpsee = { version = "0.26", features = ["macros", "server"] }
tower = "0.5"
log = "0.4"
notify = { version = "8", optional = true }
paste = "1"
rand = "0.10"
redis = { version = "1", features = ["aio", "connection-manager", "tokio-comp", "tokio-rustls-comp"] }
ref-map = "0.2"
regex = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
rsmq_async = "18"
rust-s3 = { version = "0.37", features = ["with-tokio", "tokio-rustls-tls"], default-features = false }
rust-otp = "3"
sea-orm = { version = "2", features = ["sqlx-postgres", "runtime-tokio-rustls", "postgres-array", "stream", "macros", "with-json", "with-time"], default-features = false }
sea-query = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
static_assertions = "1.1"
str-macro = "1"
strum = "0.28"
strum_macros = "0.28"
time = { version = "0.3", features = ["macros", "parsing", "serde"], default-features = false }
tiny-keccak = { version = "2", features = ["k12"] }
toml = { version = "1.1", features = ["parse"] }
tokio = { version = "1", features = ["fs", "io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }
typenum = "1"
uuid = { version = "1", features = ["v4"] }
unic-langid = "0.9"
unicase = "2"
wikidot-normalize = "0.12"
wikidot-path = "0.6"
arrayvec = "0.7.6"

[dev-dependencies]
maplit = "1"
pretty_assertions = "1"
self_cell = "1"

[build-dependencies]
built = { version = "0.8", features = ["chrono", "git2"] }

# Lints

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "deny"

[lints.clippy]
large_enum_variant = "allow"

[package.metadata.cargo-machete]
ignored = ["rust-s3"]  # renamed to s3

# Performance options

[profile.release]
lto = true
