use proc_macro2::Span;
use syn::parse::ParseStream;
use syn::token::Pub;
use syn::{LitBool, Token, Visibility};

/// Designates how this method should be generated by the macro.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum GenerateMethod {
    /// Implement a public method to be used.
    PublicImpl,

    /// Implement a private "inner" method as a helper.
    PrivateImpl,

    /// Don't implement the method or struct, have the caller do it themselves.
    NoImpl,
}

impl GenerateMethod {
    pub fn parse(input: ParseStream) -> syn::Result<Self> {
        let token = input.lookahead1();
        if token.peek(LitBool) {
            let t_bool: LitBool = input.parse()?;
            if t_bool.value {
                Ok(GenerateMethod::PublicImpl)
            } else {
                Ok(GenerateMethod::PrivateImpl)
            }
        } else if token.peek(Token![extern]) {
            let _: Token![extern] = input.parse()?;
            Ok(GenerateMethod::NoImpl)
        } else {
            Err(token.error())
        }
    }

    pub fn into_vis_and_suffix(self) -> Option<(Visibility, &'static str)> {
        match self {
            GenerateMethod::PublicImpl => Some((public(), "")),
            GenerateMethod::PrivateImpl => Some((private(), "_inner")),
            GenerateMethod::NoImpl => None,
        }
    }
}

impl Default for GenerateMethod {
    #[inline]
    fn default() -> Self {
        GenerateMethod::PublicImpl
    }
}

#[inline]
fn public() -> Visibility {
    Visibility::Public(Pub(Span::call_site()))
}

#[inline]
fn private() -> Visibility {
    Visibility::Inherited
}
