use syn::parse::{Lookahead1, ParseStream};
use syn::{LitBool, Token};

/// Designates how this method should be generated by the macro.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum GenerateMethod {
    /// Implement a public method to be used.
    ImplPublic,

    /// Implement a private "inner" method as a helper.
    ImplPrivate,

    /// Don't implement anything, have the caller do it themselves.
    NoImpl,
}

impl GenerateMethod {
    pub fn parse(input: ParseStream, token: Lookahead1) -> syn::Result<Self> {
        if token.peek(LitBool) {
            let t_bool: LitBool = input.parse()?;
            if t_bool.value {
                Ok(GenerateMethod::ImplPublic)
            } else {
                Ok(GenerateMethod::NoImpl)
            }
        } else if token.peek(Token![fn]) {
            let _: Token![fn] = input.parse()?;
            Ok(GenerateMethod::ImplPrivate)
        } else {
            Err(token.error())
        }
    }
}

impl Default for GenerateMethod {
    #[inline]
    fn default() -> Self {
        GenerateMethod::ImplPublic
    }
}
