services:
  database:
    build:
      context: ../..
      dockerfile: install/local/postgres/Dockerfile
    environment:
      - "POSTGRES_DB=wikijump"
      - "POSTGRES_USER=wikijump"
      - "POSTGRES_PASSWORD=wikijump"
      - "POSTGRES_HOST_AUTH_METHOD=md5"
      - "POSTGRES_INITDB_ARGS=--locale en_US.UTF-8"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 10s
      timeout: 5s
      retries: 6

  files:
    build: minio
    restart: unless-stopped
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=defaultpassword"
      - "MINIO_REGION_NAME=local"
      - "INITIAL_BUCKETS=deepwell-files deepwell-text-blocks"
      - "DATA_DIR=/data"  # You can add a volume for /data if you wish
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    build: valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    # You can add a volume for /data if you wish
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  deepwell:
    build:
      context: ../..
      dockerfile: install/local/deepwell/Dockerfile
    ports:
      - "2747:2747"
    environment:
      - "DATABASE_URL=postgres://wikijump:wikijump@database/wikijump"
      - "REDIS_URL=redis://cache"
      - "S3_FILES_BUCKET=deepwell-files"
      - "S3_TEXT_BLOCKS_BUCKET=deepwell-text-blocks"
      - "S3_REGION_NAME=local"
      - "S3_PATH_STYLE=true"
      - "S3_CUSTOM_ENDPOINT=http://files:9000"
      - "S3_ACCESS_KEY_ID=minio"
      - "S3_SECRET_ACCESS_KEY=defaultpassword"
      - "DEEPWELL_BUILD_PROFILE=${DEEPWELL_BUILD_PROFILE:-debug}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 600s
      start_interval: 10s
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
      files:
        condition: service_healthy

  framerail:
    build:
      context: ../..
      dockerfile: install/local/framerail/Dockerfile
    ports:
      - "3393:3393"
    environment:
      - "DEEPWELL_HOST=deepwell"
      - "FRAMERAIL_MODE=${FRAMERAIL_MODE:-dev}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 2s
      retries: 3
    depends_on:
      deepwell:
        condition: service_started

  wws:
    build:
      context: ../..
      dockerfile: install/local/wws/Dockerfile
    ports:
      - "3466:3466"
    environment:
      - "ADDRESS=[::]:3466"
      - "DEEPWELL_URL=http://deepwell:2747"
      - "REDIS_URL=redis://cache"
      - "S3_FILES_BUCKET=deepwell-files"
      - "S3_TEXT_BLOCKS_BUCKET=deepwell-text-blocks"
      - "S3_REGION_NAME=local"
      - "S3_PATH_STYLE=true"
      - "S3_CUSTOM_ENDPOINT=http://files:9000"
      - "S3_ACCESS_KEY_ID=minio"
      - "S3_SECRET_ACCESS_KEY=defaultpassword"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 600s
      start_interval: 10s
    depends_on:
      deepwell:
        condition: service_healthy
      cache:
        condition: service_healthy
      files:
        condition: service_healthy

  caddy:
    build:
      context: ../..
      dockerfile: install/local/caddy/Dockerfile
    volumes:
      - local-caddy-data:/data
      - local-caddy-config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wikijump-health-check"]
      interval: 30s
      timeout: 2s
      retries: 3

volumes:
  local-caddy-data:
    name: local-caddy-data
  local-caddy-config:
    name: local-caddy-config
