services:
  deepwell:
    volumes:
      # Rust sources
      - type: bind
        source: ../../deepwell/src
        target: /src/deepwell/src
        read_only: true
      - type: bind
        source: ../../deepwell/build.rs
        target: /src/deepwell/build.rs
        read_only: true
      - type: bind
        source: ../../deepwell/Cargo.toml
        target: /src/deepwell/Cargo.toml
        read_only: true
      # Database files
      - type: bind
        source: ../../deepwell/migrations
        target: /src/deepwell/migrations
        read_only: true
      - type: bind
        source: ../../deepwell/seeder
        target: /src/deepwell/seeder
        read_only: true
      # Configuration data
      - type: bind
        source: ../../deepwell/askama.toml
        target: /src/deepwell/askama.toml
        read_only: true
      - type: bind
        source: ../../install/local/deepwell/config.toml
        target: /etc/deepwell.toml
      # Translation data
      - type: bind
        source: ../../locales
        target: /opt/locales
        read_only: true

  framerail:
    environment:
      - "WIKIDOT_APP_NAME"
      - "WIKIDOT_API_KEY"
      - "WIKIDOT_XMLRPC_OWNER_USERNAME"
      - "XML_RPC_USERNAME"
      - "XML_RPC_PASSWORD"
      - "XML_RPC_WRITE_USERNAME"
      - "XML_RPC_WRITE_PASSWORD"
    volumes:
      # Typescript/Svelte files
      - type: bind
        source: ../../framerail/src
        target: /app/src
        read_only: true
      - type: bind
        source: ../../framerail/static
        target: /app/static
        read_only: true
      - type: bind
        source: ../../framerail/package.json
        target: /app/package.json
        read_only: true
      - type: bind
        source: ../../framerail/pnpm-lock.yaml
        target: /app/pnpm-lock.yaml
        read_only: true
      - type: bind
        source: ../../framerail/svelte.config.js
        target: /app/svelte.config.js
        read_only: true
      - type: bind
        source: ../../framerail/vite.config.ts
        target: /app/vite.config.ts
        read_only: true
      # Assets
      - type: bind
        source: ../../assets
        target: /app/src/assets
        read_only: true

  wws:
    volumes:
      # Rust sources
      - type: bind
        source: ../../wws/src
        target: /src/wws/src
        read_only: true
      - type: bind
        source: ../../wws/build.rs
        target: /src/wws/build.rs
        read_only: true
      - type: bind
        source: ../../wws/Cargo.toml
        target: /src/wws/Cargo.toml
        read_only: true
