<?php

namespace Wikidot\Config;

class ForbiddenNames {

    public static $sites = [
        '/^www[0-9]*$/',
        '/^[0-9]*www$/',
        '/^www\-/',
        '/^mail$/',
        '/^ftp$/',
        '/^http[s]?$/',
        '/^\-/',
        '/\-$/',
        '/^_/',
        '/_$/',
        '/^dev$/',
        '/^staging$/',
        '/^prod$/',
        '/^production$/',
        '/^admin$/',
        '/^root$/',
        '/^error$/',
        '/^null$/',
        '/^undefined$/',
        '/^blog$/',
        '/^support$/',
        '/^helpdesk$/',
        '/wikidot/',
        '/wikijump/',
        '/^pro$/',
        '/^mail$/',
        '/^film$/',
        '/^porn/',
        '/^spam/',
        '/^web$/',
        '/^ssl$/',
        '/^tls$/',
        '/^payment[s]?$/',
        '/^pay$/',
        '/^secure$/',
        '/^service[s]?$/',
        '/^static[0-9]*/',
        '/^img$/',
        '/^image[s]?$/',
        '/^stat[s]?$/',
        '/^your\-?site$/',
        '/^template\-/',
        '/^your\-?wiki$/',
        '/^wdupload$/',
        '/^wjupload$/',
        '/^file[s]?$/',
        '/^api[0-9]*/',
    ];

    public static $users = [
        '/^www[0-9]*$/',
        '/^[0-9]*www$/',
        '/^mail$/',
        '/^\-/',
        '/\-$/',
        '/^dev$/',
        '/^blog$/',
        '/^support$/',
        '/^helpdesk$/',
        '/wikidot/',
        '/wikijump/',
        '/^pro$/',
        '/^web$/',
        '/^ssl$/',
        '/^tls$/',
        '/^payment[s]?$/',
        '/^pay$/',
        '/^secure$/',
        '/^service[s]?$/',
        '/^guru$/',
        '/^admin$/',
        '/^administrator$/',
        '/^mod$/',
        '/^moderator$/',
        '/^staff$/',
        '/^anon$/',
        '/^anonymous$/',
        '/^unknown$/',
        '/^unknown (author|user|writer|person)$/',
        '/^guest/',
        '/^root$/',
        '/^error$/',
        '/^null$/',
        '/^undefined$/',
        '/^bot$/',
        '/^robot$/',
        '/^O5-\w+$/',
        '/^SCP-\w+$/',
'/^bauerbach\w+$/',
      '/^brandonfave\w+$/',  
'/^bradleya\w+$/',
     '/^DrAuerbach\w+$/',   
      '/^Dr Auerbach\w+$/',  
        '/^ishmonger\w+$/',
        '/^CFOperator\w+$/',
    ];

}
