<?php

namespace Wikidot\Config;

const forbiddenUserNames = [
    '/^www[0-9]*$/',
    '/^[0-9]*www$/',
    '/^mail$/',
    '/^\-/',
    '/\-$/',
    '/^dev$/',
    '/^blog$/',
    '/^support$/',
    '/^helpdesk$/',
    '/wikidot/',
    '/wikijump/',
    '/^pro$/',
    '/^web$/',
    '/^ssl$/',
    '/^tls$/',
    '/^payment[s]?$/',
    '/^pay$/',
    '/^secure$/',
    '/^service[s]?$/',
    '/^guru$/',
    '/^admin$/',
    '/^administrator$/',
    '/^mod$/',
    '/^moderator$/',
    '/^staff$/',
    '/^anon$/',
    '/^anonymous$/',
    '/^unknown$/',
    '/^unknown (author|user|writer|person)$/',
    '/^guest/',
    '/^root$/',
    '/^error$/',
    '/^null$/',
    '/^undefined$/',
    '/^bot$/',
    '/^robot$/',
    '/^O5-\w+$/',
    '/^SCP-\w+$/',
];
