/*
 * services/relation/mod.rs
 *
 * DEEPWELL - Wikijump API provider and database manager
 * Copyright (C) 2019-2026 Wikijump Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

//! A service to manage "relations", which are relationships between entities.
//!
//! A "relation" is a pair of two IDs and the relation type, along with optional
//! associated JSON metadata.
//!
//! Instead of needing to create a separate table for user blocks or site membership,
//! we can instead define a number of relations using the relation system.
//!
//! For example:
//! * `site` / `member` / `user` &mdash; User is a site member
//! * `user` / `block` / `user` &mdash; User has blocked another user
//! * `page` / `star` / `user` &mdash; User has starred a page

#[macro_use]
mod macros;

mod page_attribution;
mod page_star;
mod page_watch;
mod site_ban;
mod site_member;
mod site_user;
mod structs;
mod user_block;
mod user_bot_owner;
mod user_contact;
mod user_follow;

pub use self::page_attribution::{
    ClearPageAttributions, GetPageAttributions, PageAttribution, PageAttributionEntry,
    PageAttributionKind, PageAttributionMetadata, SetPageAttributions,
};
pub use self::page_star::{CreatePageStar, GetPageStar, RemovePageStar};
pub use self::page_watch::{CreatePageWatch, GetPageWatch, RemovePageWatch};
pub use self::site_ban::{CreateSiteBan, GetSiteBan, RemoveSiteBan, SiteBanData};
pub use self::site_member::{
    CreateSiteMember, GetSiteMember, RemoveSiteMember, SiteMemberAccepted, SiteMemberData,
};
pub use self::site_user::CreateSiteUser;
pub use self::structs::{
    RelationDirection, RelationObject, RelationReference, relation_condition,
    relation_type_condition,
};
pub use self::user_block::{
    CreateUserBlock, GetUserBlock, RemoveUserBlock, UserBlockData,
};
pub use self::user_bot_owner::{
    CreateSingleUserBotOwner, RemoveUserBotOwner, UserBotMetadata, UserBotOwner,
};
pub use self::user_follow::RemoveUserFollow;

use crate::error::prelude::{Error, ErrorType, Result, ResultExt};
use crate::models::relation::{self, Entity as Relation, Model as RelationModel};
use crate::services::ServiceContext;
use crate::services::permission::PermissionCache;
use crate::types::{RelationObjectType, RelationType};
use crate::utils::now;
use paste::paste;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, Condition, EntityTrait, QueryFilter, QueryOrder, Set,
};
use serde::Serialize;

// Base service exists here.
//
// Methods and types per-relation are in their respective submodules,
// and are mostly generated by macros.

#[derive(Debug)]
pub struct RelationService;

impl RelationService {
    pub async fn create<M: Serialize>(
        ctx: &ServiceContext<'_>,
        relation_type: RelationType,
        dest: RelationObject,
        from: RelationObject,
        created_by: i64,
        metadata: &M,
    ) -> Result<RelationModel> {
        debug!("Create relation for {dest:?} ← {relation_type:?} ← {from:?}");

        let make_error = || {
            Error::new(
                format!(
                    "failed to create relation {:?} ← {:?} ← {:?}",
                    dest, relation_type, from,
                ),
                ErrorType::Relation,
            )
        };

        // Relations are not permitted to point to themselves
        if dest == from {
            error!(
                "Source and destination are the same: {:?}, cannot create relation",
                dest,
            );
            bail!(Error::new(
                format!(
                    "cannot create relation, source and destination are the same: {:?}",
                    dest
                ),
                ErrorType::BadRequest
            ));
        }

        // Get previous relation, if present
        let txn = ctx.transaction();
        if let Some(relation) = Self::get_optional(
            ctx,
            RelationReference::Relationship {
                relation_type,
                dest,
                from,
            },
        )
        .await
        .or_raise(make_error)?
        {
            debug!("Relation already exists, marking old item overwritten");
            let model = relation::ActiveModel {
                relation_id: Set(relation.relation_id),
                overwritten_at: Set(Some(now())),
                overwritten_by: Set(Some(created_by)),
                ..Default::default()
            };

            model.update(txn).await.or_raise(make_error)?;
        }

        // Insert new relation
        let (dest_type, dest_id) = dest.into();
        let (from_type, from_id) = from.into();
        relation_type.types().check(dest_type, from_type);

        let metadata = serde_json::to_value(metadata).or_raise(make_error)?;
        let model = relation::ActiveModel {
            relation_type: Set(relation_type),
            dest_type: Set(dest_type),
            dest_id: Set(dest_id),
            from_type: Set(from_type),
            from_id: Set(from_id),
            metadata: Set(metadata),
            created_by: Set(created_by),
            ..Default::default()
        };

        let relation = model.insert(txn).await.or_raise(make_error)?;
        Self::invalidate_permission_cache_for_relation(ctx, &relation)
            .await
            .or_raise(make_error)?;
        Ok(relation)
    }

    pub async fn remove(
        ctx: &ServiceContext<'_>,
        reference: RelationReference,
        deleted_by: i64,
    ) -> Result<RelationModel> {
        debug!("Removing relation for {reference:?}");

        let txn = ctx.transaction();
        let relation_id = Self::get_id(ctx, reference)
            .await
            .or_raise(|| Error::new("failed to remove relation", ErrorType::Relation))?;

        let make_error = || {
            Error::new(
                format!(
                    "failed to remove relation ID {}, done by user ID {}",
                    relation_id, deleted_by,
                ),
                ErrorType::Relation,
            )
        };

        let model = relation::ActiveModel {
            relation_id: Set(relation_id),
            deleted_at: Set(Some(now())),
            deleted_by: Set(Some(deleted_by)),
            ..Default::default()
        };

        let output = model.update(txn).await.or_raise(make_error)?;
        Self::invalidate_permission_cache_for_relation(ctx, &output)
            .await
            .or_raise(make_error)?;
        Ok(output)
    }

    async fn invalidate_permission_cache_for_relation(
        ctx: &ServiceContext<'_>,
        relation: &RelationModel,
    ) -> Result<()> {
        match (
            relation.relation_type,
            relation.dest_type,
            relation.from_type,
        ) {
            (
                RelationType::SiteBan | RelationType::SiteMember,
                RelationObjectType::Site,
                RelationObjectType::User,
            ) => PermissionCache::defer_invalidate_user(
                ctx,
                relation.dest_id,
                relation.from_id,
            ),
            _ => Ok(()),
        }
    }

    pub async fn get_optional(
        ctx: &ServiceContext<'_>,
        reference: RelationReference,
    ) -> Result<Option<RelationModel>> {
        debug!("Getting relation for {reference:?}");

        let make_error = || {
            Error::new(
                format!("failed to get relation {:?}", reference),
                ErrorType::Relation,
            )
        };

        let txn = ctx.transaction();
        let relation = Relation::find()
            .filter(
                Condition::all()
                    .add(reference.condition())
                    .add(relation::Column::OverwrittenAt.is_null())
                    .add(relation::Column::DeletedAt.is_null()),
            )
            .one(txn)
            .await
            .or_raise(make_error)?;

        Ok(relation)
    }

    /// Gets the relation ID from a reference, looking up if necessary.
    pub async fn get_id(
        ctx: &ServiceContext<'_>,
        reference: RelationReference,
    ) -> Result<i64> {
        match reference {
            RelationReference::Id(relation_id) => Ok(relation_id),
            RelationReference::Relationship { .. } => {
                let RelationModel { relation_id, .. } = Self::get(ctx, reference)
                    .await
                    .or_raise(|| {
                    Error::new("failed to get relation for its ID", ErrorType::Relation)
                })?;

                Ok(relation_id)
            }
        }
    }

    pub async fn get(
        ctx: &ServiceContext<'_>,
        reference: RelationReference,
    ) -> Result<RelationModel> {
        find_or_error!(Self::get_optional(ctx, reference), "relation", Relation)
    }

    pub async fn exists(
        ctx: &ServiceContext<'_>,
        reference: RelationReference,
    ) -> Result<bool> {
        Self::get_optional(ctx, reference)
            .await
            .map(|relation| relation.is_some())
    }

    // TODO paginate
    /// Gets the history of this `dest` / `from` relation.
    ///
    /// This includes all all edits of the relation (`overwritten_at`)
    /// and deleted / remade versions of the relation (`deleted_at`).
    pub async fn get_history(
        ctx: &ServiceContext<'_>,
        relation_type: RelationType,
        dest: RelationObject,
        from: RelationObject,
    ) -> Result<Vec<RelationModel>> {
        info!("Getting history of relations for {dest:?} ← {relation_type:?} ← {from:?}");

        let make_error = || {
            Error::new(
                format!(
                    "failed to get history of relation {:?} ← {:?} ← {:?}",
                    dest, relation_type, from,
                ),
                ErrorType::Relation,
            )
        };

        let txn = ctx.transaction();
        let relations = Relation::find()
            .filter(relation_condition(relation_type, dest, from))
            .order_by_asc(relation::Column::CreatedAt)
            .all(txn)
            .await
            .or_raise(make_error)?;

        Ok(relations)
    }

    // TODO paginate
    /// Gets all relations from the starting object in the given direction.
    ///
    /// For instance, this can be used to get all blocked users, or all users who are blocking
    /// someone depending on the `RelationDirection`.
    pub async fn get_entries(
        ctx: &ServiceContext<'_>,
        relation_type: RelationType,
        object: RelationObject,
        direction: RelationDirection,
    ) -> Result<Vec<RelationModel>> {
        info!("Getting {direction:?} relations for {object:?} / {relation_type:?}");

        let make_error = || {
            Error::new(
                format!(
                    "failed to get history of relation {:?} / {:?}",
                    object, relation_type,
                ),
                ErrorType::Relation,
            )
        };

        let (object_type, object_id) = object.into();
        let (object_type_column, object_id_column) = match direction {
            RelationDirection::Dest => {
                (relation::Column::DestType, relation::Column::DestId)
            }
            RelationDirection::From => {
                (relation::Column::FromType, relation::Column::FromId)
            }
        };

        let txn = ctx.transaction();
        let relations = Relation::find()
            .filter(
                Condition::all()
                    .add(relation_type_condition(relation_type))
                    .add(object_type_column.eq(object_type))
                    .add(object_id_column.eq(object_id))
                    .add(relation::Column::DeletedAt.is_null()),
            )
            .order_by_asc(relation::Column::CreatedAt)
            .all(txn)
            .await
            .or_raise(make_error)?;

        Ok(relations)
    }
}
