# PostgreSQL

[[variable]]
name = "POSTGRES_PASSWORD"
description = "Password for the PostgreSQL database."
value = ""  # TODO: generate password value!
is_secret = true

# S3 / Object Storage

[[variable]]
name = "S3_FILES_BUCKET"
description = "Name of bucket where file / blob data will be kept."
value = "wikijump-files-dev"
is_secret = false

[[variable]]
name = "S3_TEXT_BLOCKS_BUCKET"
description = "Name of bucket where text block data will be kept."
value = "wikijump-textblocks-dev"
is_secret = false

[[variable]]
name = "S3_CUSTOM_ENDPOINT"
description = "Endpoint for S3."
value = "https://nyc3.digitaloceanspaces.com"
is_secret = false

[[variable]]
name = "S3_REGION_NAME"
description = "Region name for S3."
value = "nyc3"
is_secret = false

[[variable]]
name = "S3_PATH_STYLE"
description = "Boolean. If true, use path for bucket specification, if false, use subdomain."
value = "true"
is_secret = false

[[variable]]
name = "S3_ACCESS_KEY_ID"
description = "Access key for S3."
value = ""  # TODO: fill in value here!
is_secret = true

[[variable]]
name = "S3_SECRET_ACCESS_KEY"
description = "Secret key for S3 access."
value = ""  # TODO: fill in value here!
is_secret = true

# Mailjet API

[[variable]]
name = "MAILJET_API_KEY"
description = "API key for Mailjet."
value = ""  # TODO: fill in value here!
is_secret = true

[[variable]]
name = "MAILJET_SECRET_KEY"
description = "Secret key for Mailjet."
value = ""  # TODO: fill in value here!
is_secret = true

# ACME DNS Challenge Token
#
# This assumes you're using DigitalOcean, but any DNS provider
# listed on https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148
# will work. Remember you will need to update the "wildcard_cert" field in
# install/{dev,prod}/caddy/request.json *and* ALL uses of $DIGITALOCEAN_API_TOKEN.

[[variable]]
name = "DIGITALOCEAN_API_TOKEN"
description = "API token for changing DNS records in DigitalOcean"
value = ""  # TODO: fill in value here!
is_secret = true

# Alerters

[[variable]]
name = "DISCORD_WEBHOOK"
description = "Webhook for notifying on infrastructural changes"
value = ""  # TODO: fill in value here!
is_secret = true
