#!/bin/sh
set -e

# Run migrations
/usr/local/cargo/bin/sqlx migrate run

# Start watcher
#
# This will recompile and restart the deepwell daemon on any source changes
# The commandline being run for the daemon is "deepwell /etc/deepwell.toml".

RUN_COMMAND="run --locked -- /etc/deepwell.toml"
if [ "${DEEPWELL_BUILD_PROFILE:-debug}" = "release" ]; then
    RUN_COMMAND="run --locked --release -- /etc/deepwell.toml"
fi

exec /usr/bin/env RUST_BACKTRACE=1 \
    /usr/local/cargo/bin/cargo watch \
        --why \
        -w /src/deepwell \
        -w /opt/locales \
        -w /etc/deepwell.toml \
        -x "$RUN_COMMAND"
