<?php
declare(strict_types=1);

namespace Database\Seeders;

use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// prettier-ignore
class LegacySeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Throws Exception if random_bytes() can't collect enough entropy.
     *
     * @return void
     * @throws Exception
     */
    public function run(): void
    {
        DB::unprepared(
            <<<STATEMENT
INSERT INTO public.admin (admin_id, site_id, user_id, founder) VALUES (1, 1, 1, true);
INSERT INTO public.admin (admin_id, site_id, user_id, founder) VALUES (2, 2, 1, true);

INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (6, 2, 'nav', true, 20, true, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (14, 2, 'search', true, 20, true, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (15, 1, 'nav', true, 20, true, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (2, 2, '_default', true, 20, false, 'e:m;c:m;m:m;d:;a:m;r:m;z:;o:arm', false, 1, NULL, false, 'nav:top', 'nav:side', NULL, false, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (13, 2, 'admin', false, 21, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (17, 2, 'forum', true, 20, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (12, 2, 'system', true, 20, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (1, 1, '_default', true, 20, false, 'e:m;c:m;m:m;d:;a:m;r:m;z:;o:arm', false, 1, NULL, false, 'nav:top', 'nav:side', NULL, false, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (4, 1, 'account', false, 21, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (3, 1, 'admin', false, 21, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (16, 1, 'search', true, 20, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (5, 1, 'user', false, 21, false, 'v:arm;e:;c:;m:;d:;a:;r:;z:;o:', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (19, 1, 'system-all', true, 20, true, 'e:m;c:m;m:m;d:;a:m;r:m;z:;o:arm', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (20, 1, 'system', true, 20, true, 'e:m;c:m;m:m;d:;a:m;r:m;z:;o:arm', true, 1, NULL, true, 'nav:top', 'nav:side', NULL, NULL, true, NULL, NULL, NULL, false, NULL);
INSERT INTO public.category (category_id, site_id, name, theme_default, theme_id, permissions_default, permissions, license_default, license_id, license_other, nav_default, top_bar_page_name, side_bar_page_name, template_id, per_page_discussion, per_page_discussion_default, rating, category_template_id, theme_external_url, autonumerate, page_title_template) VALUES (21, 1, 'auth', true, 20, false, 'e:m;c:m;m:m;d:;a:m;r:m;z:;o:arm', false, 1, NULL, false, 'nav:top', 'nav:side', NULL, false, true, NULL, NULL, NULL, false, NULL);

INSERT INTO public.forum_settings (site_id, permissions, per_page_discussion, max_nest_level) VALUES (2, 't:m;p:m;e:o;s:', false, 2);


INSERT INTO public.profile (user_id, real_name, pronouns, birthday_day, birthday_month, birthday_year, about, location, website, im_icq, im_jabber, change_screen_name_count) VALUES (1, NULL, NULL, NULL, NULL, NULL, 'Wikidot administrator.', NULL, NULL, NULL, NULL, 0);

INSERT INTO public.site (site_id, name, subtitle, unix_name, description, language, date_created, custom_domain, visible, default_page, private, deleted) VALUES (1, 'Wikijump', 'Fighting Ozone Pollution', 'www', 'Wikijump host site', 'en', NULL, NULL, true, 'start', false, false);
INSERT INTO public.site (site_id, name, subtitle, unix_name, description, language, date_created, custom_domain, visible, default_page, private, deleted) VALUES (2, 'Template site (en)', 'Default template wiki', 'template-en', '', 'en', NULL, NULL, true, 'start', false, false);

INSERT INTO public.site_settings (site_id, allow_membership_by_apply, allow_membership_by_password, membership_password, file_storage_size, use_ganalytics, private_landing_page, max_private_members, max_private_viewers, hide_navigation_unauthorized, ssl_mode, allow_members_invite, max_upload_file_size) VALUES (1, true, false, NULL, 1073741824, false, 'system:join', 50, 20, true, NULL, false, 10485760);
INSERT INTO public.site_settings (site_id, allow_membership_by_apply, allow_membership_by_password, membership_password, file_storage_size, use_ganalytics, private_landing_page, max_private_members, max_private_viewers, hide_navigation_unauthorized, ssl_mode, allow_members_invite, max_upload_file_size) VALUES (2, false, false, '', 314572800, false, 'system:join', 50, 20, true, NULL, false, 10485760);

INSERT INTO public.site_tag (tag_id, site_id, tag) VALUES (1, 2, 'template');

INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (1, 'Base', 'base', true, NULL, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (2, 'Clean', 'clean', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (4, 'Flannel', 'flannel', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (6, 'Flannel Ocean', 'flannel-ocean', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (8, 'Flannel Nature', 'flannel-nature', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (10, 'Cappuccino', 'cappuccino', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (12, 'Gila', 'gila', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (14, 'Co', 'co', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (15, 'Flower Blossom', 'flower-blossom', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (16, 'Localize', 'localize', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (20, 'Webbish', 'webbish2', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (3, 'Clean - no side bar', 'clean-no-side-bar', false, 2, 2, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (5, 'Flannel - no side bar', 'flannel-no-side-bar', false, 4, 4, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (7, 'Flannel Ocean - no side bar', 'flannel-ocean-no-side-bar', false, 6, 6, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (9, 'Flannel Nature - no side bar', 'flannel-nature-no-side-bar', false, 8, 8, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (11, 'Cappuccino - no side bar', 'cappuccino-no-side-bar', false, 10, 10, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (13, 'Gila - no side bar', 'gila-no-side-bar', false, 12, 12, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (17, 'Localize - no side bar', 'localize-no-side-bar', false, 16, 16, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (18, 'Flower Blossom - no side bar', 'flower-blossom-no-side-bar', false, 15, 15, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (19, 'Co - no side bar', 'co-no-side-bar', false, 14, 14, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (21, 'Webbish - no side bar', 'webbish2-no-side-bar', false, 20, 20, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (22, 'Shiny', 'shiny', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (23, 'Shiny - no side bar', 'shiny-no-side-bar', false, 22, 22, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (24, 'Bloo', 'bloo', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (25, 'Bloo - no side bar', 'bloo-no-side-bar', false, 24, 24, false, NULL, false, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (26, 'Basic', 'basic', false, 1, NULL, false, NULL, true, true, 0, NULL, 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (28, 'Black Highlighter', 'bhl', false, 1, NULL, true, 1, true, true, 0, '', 0);
INSERT INTO public.theme (theme_id, name, unix_name, abstract, extends_theme_id, variant_of_theme_id, custom, site_id, use_side_bar, use_top_bar, sort_index, sync_page_name, revision_number) VALUES (27, 'Sigma-9', 'sigma9', false, 1, NULL, true, 1, true, true, 0, '', 0);

INSERT INTO public.user_karma (user_id, points, level) VALUES (1, 110, 2);

INSERT INTO public.user_settings (user_id, receive_invitations, receive_pm, notify_online, notify_feed, notify_email, receive_newsletter, receive_digest, allow_site_newsletters_default, max_sites_admin) VALUES (1, true, 'a    ', '*', '*', NULL, true, true, true, 3);
STATEMENT

        );
    }
}
