name: '[backend] Docker build Framerail (prod)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/prod/framerail/Dockerfile'
      - '.github/workflows/docker-build-framerail.prod.yaml'
      - '.github/workflows/docker-build-template.yaml'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/framerail
      image-name: framerail
      tier: prod
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
