name: '[backend] Docker build Silo (local)'

on:
  pull_request:
    paths:
      - 'install/local/silo/*'
      - '.github/workflows/docker-build-silo.local.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: cd install/local/silo && docker build .
        env:
          DOCKER_BUILDKIT: 1
