name: '[backend] Docker build Caddy (dev)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/dev/caddy/*'
      - '.github/workflows/docker-build-caddy.dev.yaml'

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/caddy
      image-name: caddy
      tier: dev
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
