name: '[backend] Docker build WWS (prod)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/prod/wws/Dockerfile'
      - '.github/workflows/docker-build-wws.prod.yaml'
      - '.github/workflows/docker-build-template.yaml'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/wws
      image-name: wws
      tier: prod
