name: '[backend] Docker build WWS (local)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/local/wws/Dockerfile'
      - '.github/workflows/docker-build-wws.local.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -f install/local/wws/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
