name: '[backend] Docker build DEEPWELL (prod)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/prod/deepwell/Dockerfile'
      - '.github/workflows/docker-build-deepwell.prod.yaml'
      - '.github/workflows/docker-build-template.yaml'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/deepwell
      image-name: deepwell
      tier: prod
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
