name: '[backend] Docker build Minio (local)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/local/minio/*'
      - '.github/workflows/docker-build-minio.local.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: cd install/local/minio && docker build .
        env:
          DOCKER_BUILDKIT: 1
