name: '[backend] Docker build PostgreSQL (local)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'web/database/**'
      - 'install/common/postgres/**'
      - 'install/local/postgres/Dockerfile'
      - '.github/workflows/docker-build-postgres.local.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -f install/local/postgres/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
