name: '[backend] Docker build DEEPWELL (local)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/local/deepwell/Dockerfile'
      - '.github/workflows/docker-build-deepwell.local.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -f install/local/deepwell/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
