name: '[backend] Docker build WWS (dev)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/dev/wws/Dockerfile'
      - '.github/workflows/docker-build-wws.dev.yaml'

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/wws
      image-name: wws
      tier: dev
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
