name: '[backend] Docker build Caddy (DEV)'

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - 'install/dev/caddy/*'
      - '.github/workflows/docker-build-caddy.dev.yaml'

env:
  PUBLIC_ALIAS: w6h1w4k8
  IMAGE_NAME: wikijump/caddy
  DESCRIPTION: Caddy server configured for Wikijump
  NAME: caddy
  TIER: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        if: false
        run: docker build --tag ${{ env.IMAGE_NAME }}:${{ env.TIER }} -f install/${{ env.TIER }}/${{ env.NAME }}/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build and push image to ECR Public
        uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
        env:
          DOCKER_BUILDKIT: 1
        with:
          dockerfile: install/${{ env.TIER }}/${{ env.NAME }}/Dockerfile
          context: .
          tags: |
            public.ecr.aws/${{ env.PUBLIC_ALIAS }}/${{ env.IMAGE_NAME }}:${{ env.TIER }}
