name: '[backend] Docker build Caddy (local)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'install/local/caddy/*'
      - '.github/workflows/docker-build-caddy.local.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -f install/local/caddy/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1
