name: '[backend] Docker build Minio'

on:
  push:
    branches:
      - develop
    paths:
      - 'install/local/minio/*'
      - '.github/workflows/docker-push-minio.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scpwiki/wikijump
  DESCRIPTION: Modified version of Minio for integration testing
  TAG: minio

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.TAG }},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
          labels: |
            org.opencontainers.image.title=${{ env.NAME }}
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      - name: Build and push image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: install/local/minio/Dockerfile
          context: install/local/minio
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/develop' }}
