name: '[framerail] Typescript'

on:
  pull_request:
    paths:
      - 'framerail/**'
      - '.github/workflows/framerail.yaml'
  push:
    branches:
      - develop
      - prod

permissions:
  contents: read

jobs:
  build_and_lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: framerail/pnpm-lock.yaml

      - name: Install dependencies
        run: cd framerail && pnpm install --frozen-lockfile

      - name: Build
        run: cd framerail && pnpm build

      - name: Lint
        run: cd framerail && pnpm lint
