name: '[python] Importer Scripts'

on:
  pull_request:
    paths:
      - 'deepwell/importer/*.py'
      - '.github/workflows/importer.yaml'
  push:
    branches:
      - develop
      - prod

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # update this as needed
        python-version:
          - '3.12'
          - '3.13'
          - '3.14'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install mypy ruff

      - name: ruff format
        run: cd deepwell && ruff format importer

      - name: ruff check
        run: cd deepwell && ruff check importer

      - name: mypy
        run: cd deepwell && mypy importer
