name: '[komodo] Deploy Dev'

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  # Wait for image push jobs to complete
  # See https://stackoverflow.com/a/75597437
  caddy:
    if: ${{ github.repository == 'scpwiki/wikijump' }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/caddy
      image-name: caddy
      tier: dev
      push: true
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}

  deepwell:
    if: ${{ github.repository == 'scpwiki/wikijump' }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/deepwell
      image-name: deepwell
      tier: dev
      push: true
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}

  framerail:
    if: ${{ github.repository == 'scpwiki/wikijump' }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/framerail
      image-name: framerail
      tier: dev
      push: true
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}

  wws:
    if: ${{ github.repository == 'scpwiki/wikijump' }}
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image-repository: wikijump/wws
      image-name: wws
      tier: dev
      push: true
    secrets:
      aws-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
      aws-secret-key: ${{ secrets.AWS_ECR_SECRET_KEY }}

  # Then send webhook notification for Komodo to deploy.
  #
  # This ensures that all images are built and pushed up before
  # attempting to redeploy the stack.
  notify_komodo:
    if: ${{ github.repository == 'scpwiki/wikijump' }}
    name: Deploy Komodo (dev)
    runs-on: ubuntu-latest
    needs: [caddy, deepwell, framerail, wws]
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.KOMODO_DEPLOY_DEV_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.KOMODO_DEPLOY_DEV_WEBHOOK_SECRET }}
