name: '[l10n] Localization'

on:
  pull_request:
    paths:
      - 'locales/**'
      - '.github/workflows/locales.yaml'
  push:
    branches:
      - develop
      - prod

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            locales/validator/target
          key: ${{ runner.os }}-locales-default-${{ hashFiles('locales/validator/**/Cargo.toml') }}

      - name: Run Check
        run: cd locales/validator && cargo run --locked

  clippy_lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -A unused -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            locales/validator/target
          key: ${{ runner.os }}-locales-lint-${{ hashFiles('locales/validator/**/Cargo.toml') }}

      - name: Rustfmt
        run: cd locales/validator && cargo fmt --all -- --check

      - name: Clippy
        run: cd locales/validator && cargo clippy --locked --tests --no-deps
