name: '[wws] Rust'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    paths:
      - 'wws/Cargo.toml'
      - 'wws/Cargo.lock'
      - 'wws/src/**'
      - 'wws/tests/**'
      - '.github/workflows/wws.yaml'
      - '.github/codecov.yml'
  push:
    branches:
      - develop
      - prod
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  binary_build_and_test:
    name: Build, Test and Coverage
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'full-ci') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            wws/target
          key: ${{ runner.os }}-wws-default-${{ hashFiles('wws/**/Cargo.toml') }}

      - name: Build
        run: cd wws && cargo build

      - name: Test
        run: cd wws && cargo test --all-features -- --nocapture --test-threads 1

      - name: Generate Coverage
        run: |
          cd wws && cargo +nightly tarpaulin --all-features --workspace --timeout 120 --out xml --output-dir target/coverage

      - name: Export Coverage
        # codecov/codecov-action v5.5.5
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac
        with:
          use_oidc: true
          slug: Rokurolize/wikijump
          files: wws/target/coverage/cobertura.xml
          flags: wws
          disable_search: true
          fail_ci_if_error: true

  clippy_lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            wws/target
          key: ${{ runner.os }}-wws-lint-${{ hashFiles('wws/**/Cargo.toml') }}

      - name: Install cargo-machete
        run: cargo install cargo-machete --version 0.9.1 --locked

      - name: Machete
        run: cargo machete wws

      - name: Rustfmt
        run: cd wws && cargo fmt --all -- --check

      - name: Clippy
        run: cd wws && cargo clippy --tests --no-deps
